import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Uii from '@/providers/Uii'
import { ClerkProvider } from '@clerk/nextjs'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Events by FF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <Uii>
          {children}
        </Uii>
      </body>
    </html>
    </ClerkProvider>
  )
}
